default_stages: [commit, push]
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: detect-aws-credentials
-   repo: https://github.com/PyCQA/flake8
    rev: '6027577'
    hooks:
    -   id: flake8
        exclude: (tests|script)
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.10
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: '0b037c2'
    hooks:
    -   id: mypy
        exclude: ^doc/
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.1.0
    hooks:
    -    id: commitlint
         stages: [commit-msg]
