name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17.x"
      - name: Simulate a Release
        run: |
          npm install -g semantic-release                 \
          "@semantic-release/changelog"                   \
          "@semantic-release/commit-analyzer"             \
          "@semantic-release/github"                      \
          "@semantic-release/release-notes-generator"
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
